### ISSUE TITLE
Possibility to lock armorstands and itemframes.

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#15]
Would it be possible to implement the ability to lock armorstands and item frames (entities/tiles)?

**Comment by dmulloy2** [comment]
It appears to be possible: https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162/

However I'm extremely busy right now, so I don't necessarily have the time to implement something like this.

**Comment by mibby** [comment]
No problem. As long as it is something that can be taken into consideration for the future. I did see that fork but it happened to be quite buggy the last time I used it, not compiled against the latest upstream source, and not open-source itself.
