### ISSUE TITLE
Having issues using your maven repo for the LWC dependency

### ISSUE THREAD

**Issue by RoboMWM** [dmulloy2/LWC#23]
`Failed to collect dependencies at com.griefcraft:lwc:jar:4.6.0-SNAPSHOT: Failed to read artifact descriptor for com.griefcraft:lwc:jar:4.6.0-SNAPSHOT`

Full log: https://gist.github.com/RoboMWM/6ba7319650ba454448e9be206724f117

**Comment by RoboMWM** [comment]
In the meantime, I've used this from jitpack:

```
<dependency>
            <groupId>com.github.dmulloy2.LWC</groupId>
            <artifactId>lwc</artifactId>
            <version>master-4.5.1-g2100b5e-18</version>
        </dependency>
```

**Comment by dmulloy2** [comment]
That's really odd, it's definitely there: http://repo.dmulloy2.net/nexus/#browse/search=keyword%3DLWC:912d0fe7b81923920981139352ce9131

**Comment by RoboMWM** [comment]
Yea, I did later ensure the other maven repos didn't have release appended, and it just failed with the same message along with being unable to find it in the paper-repo (e.g. nothing about not allowing SNAPSHOT). So I'm guessing it's not liking your pom.xml in it?
