### ISSUE TITLE
LWC Partially Functional

### ISSUE THREAD

**Issue by topthat177** [dmulloy2/LWC#25]
Hey, Im running the latest version of LWC 4.5.1 and I deleted my lib folder and restarted. /cprivate and the majority of the other functions just don't work at all suddenly. I'm opped with all perms and doing /cprivate brings up the message that I need to left click the block I wish to protect, however left clicking or does nothing and right clicking uses the door/chest or whatever. Do I need to get the seperate entities plugin? Some help would be appreciated on this one!

**Comment by topthat177** [comment]
/cremove works strangely but cannot re protect?

**Comment by dmulloy2** [comment]
Are you getting any errors in the console?

**Comment by topthat177** [comment]
Not that I can see? It just didn't work. I tried updating to the entities unofficial thing and it did the same thing. Now I'm using blocklocker which does pretty much the same thing and is just as easy if not easier.

**Comment by Pugabyte** [comment]
Just to confirm, you deleted the lib folder; mine has what appears to be sql drivers in it. Did it regenerate?

**Comment by topthat177** [comment]
Yer I deleted it. Deleted the whole plugin to be exact and reinstalled the Entities unofficial and all seems to be working now. Strange but, Ill post again if I have any more issues. Thanks guys!
