### ISSUE TITLE
Players are no longer able to right click protected iron doors to open them.

### ISSUE THREAD

**Issue by mibby** [dmulloy2/LWC#4]
LWC dev 5

RE: https://github.com/dmulloy2/LWC/commit/366753b2c5232a1305280ea73e516074893e048b#commitcomment-20636778

**Comment by PugaBear** [comment]
Can confirm

**Comment by dmulloy2** [comment]
Were they working before though? I was under the impression they weren't.

RE: https://github.com/dmulloy2/LWC/commit/0991cc37d45a128c8e37e91694451c9e8ef45f3b#commitcomment-20151947

**Comment by PugaBear** [comment]
Yes they were @dmulloy2
