### ISSUE TITLE
Publish to repo

### ISSUE THREAD

**Issue by Narimm** [dmulloy2/LWC#49]
Hi Dan

Mate I was hoping you could start publishing LWC snapshots to your nexus repo, saves me setting up a build server for it just to get the artifacts to allow my builds to proceed ok.

4.6 was the latest 

Thanks in advance

**Comment by Phoenix616** [comment]
For now I have it included this fork as the main LWC one in my repository (https://repo.minebench.de). (Only the latest version is directly from this repo though, previous versions might be from my own fork or the original one)

**Comment by dmulloy2** [comment]
Should be deploying now

**Comment by LlmDl** [comment]
What is the information I need to put into the pom.xml in order to add your LWC as a dependency?
