### ISSUE TITLE
Can't compile via maven

### ISSUE THREAD

**Issue by PugaBear** [dmulloy2/LWC#6]
http://paste.bn-mc.net/acice.pas

**Comment by dmulloy2** [comment]
You have to compile from the root LWC directory, not the core.

**Comment by PugaBear** [comment]
@dmulloy2 http://paste.bn-mc.net/agitu.rb

**Comment by dmulloy2** [comment]
````Failed to transfer file: http://repo.kitteh.org/content/groups/public/org/mcstats/bukkit/metrics/R8-SNAPSHOT/metrics-R8-20160303.160206-10.pom. Return code is: 503 , ReasonPhrase:Service Unavailable.````

Looks like kitteh repo is dead, need to find a new one or remove metrics.

**Comment by PugaBear** [comment]
Yeah, I found my way to kitteh.org's IRC and @mbaxter replied to me:
```
15:21	@mbaxter	PugaBear: That's happening because repo.kitteh.org is one of many repos in whatever you're trying to build
15:21	@mbaxter	PugaBear: And it happens to be trying repo.kitteh out of desperation, and it's failing
15:21	@mbaxter	PugaBear: repo.kitteh never held ukkit stuffs like that.
```

**Comment by dmulloy2** [comment]
Gotcha. It must be the regular mcstats repo that's down again.

**Comment by mbax** [comment]
Silly mcstats!

Maven is confusing in that you don't specify which repo a particular artifact comes from and it sorta tries them all and then reports whichever one it feels like complaining about when it can't find the artifact on any.

Is there a particular thing you're using the kitteh repo for? I slowly phased it out in the years after Bukkit's death.

**Comment by dmulloy2** [comment]
@mbax Haven't gotten around to changing it, Hidendra must've been using it for one of the millions of plugin dependencies LWC has

**Comment by mbax** [comment]
I can't quite remember anymore but there's a chance I may have hosted bPerms on there for a time. Best guess I have for a 3+ year old commit. :)

**Comment by PugaBear** [comment]
Thank you!
