### ISSUE TITLE
Iron door fix doesn't work

### ISSUE THREAD

**Issue by PugaBear** [dmulloy2/LWC#7]
@dmulloy2 It only works if you are holding a block

**Comment by dmulloy2** [comment]
The only thing I can think of is this line: https://github.com/dmulloy2/LWC/blob/master/core/src/main/java/com/griefcraft/modules/doors/DoorsModule.java#L153

But according to the JavaDoc, the action is determined by what is being clicked, not what you're clicking with: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/Action.html#RIGHT_CLICK_BLOCK

**Comment by PugaBear** [comment]
I've been trying to test but #6 is preventing that XD

**Comment by PugaBear** [comment]
@dmulloy2 I believe the event isn't being cancelled but rather being called twice, essentially opening and closing the door instantly. This would be caused by the 1.9 two hand mechanics. You'd need to use the `getHand()` method or something similar to prevent it from running twice.

**Comment by PugaBear** [comment]
Thanks again @dmulloy2! :)
