### ISSUE TITLE
iron door right click

### ISSUE THREAD

**Issue by seema84** [dmulloy2/LWC#8]
since 1.9 player can only open protected iron doors with left click. right click play the right sound but dont open the door. player in creative mode cant open this door because left click destroy the door. pls remove left click and add only right click. thanks

**Comment by dmulloy2** [comment]
Fixed in https://github.com/dmulloy2/LWC/commit/b322851a6348e3401feeb050fdc7e7222b2e1b12

**Comment by seema84** [comment]
now work both hands ... thats ok for me but i thinks only the main-hand is the best solution
